apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-yzml
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-yzml
    app.kubernetes.io/part-of: tkrw-pr712-0075-0032-app
  name: devfile-sample-yzml
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-yzml
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-yzml
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0032-tenant/tkrw-pr712-0075-0032-app/devfile-sample-yzml@sha256:315dc26a03a87490aa5d7227493d2b0f1f70465c26db69605e72752b4cf20666
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
